# Generated by Django 5.1.1 on 2025-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='FEWJ4kCycEYvTyd3CnwW8YKuhAbyj6gH', editable=False, max_length=32, unique=True),
        ),
    ]
