# Generated by Django 5.1.1 on 2025-09-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UPbB7RwB3JqxAEwnG5SKxnUmQEGca6ca', editable=False, max_length=32, unique=True),
        ),
    ]
